common:
  aws_region: us-east-1
  terraform_version: latest
  terraform_working_dir: terraform/infra
  plan_artifact_name: terraform-plan
  backend_path_template: ../config/$ENV/backend.conf
  var_file_path_template: env/$ENV/$ENV.tfvars

environments:
  dev:
    role_arn: "arn:aws:iam::820451690888:role/devops-lab-assume-role"
    backend_path: ../config/dev/backend.conf
    var_file_path: env/dev/dev.tfvars
    plan_environment_name: dev-plan
    apply_environment_name: dev-apply
  qa:
    role_arn: "xxxx"
    backend_path: ../config/qa/backend.conf
    var_file_path: env/qa/qa.tfvars
    plan_environment_name: qa-plan
    apply_environment_name: qa-apply
  prd:
    role_arn: "xxxxx"
    backend_path: ../config/prd/backend.conf
    var_file_path: env/prd/prd.tfvars
    plan_environment_name: prd-plan
    apply_environment_name: prd-apply